version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Almaty111
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  nginx-front:
    image: nginx:1.22.1
    ports:
      - "80:80"
    volumes:
      - ./front:/code
    networks:
      net:
        ipv4_address: 10.0.2.15
  nginx-back:
    image: nginx:1.22.1
    volumes:
      - ./backend:/code
    networks:
      net:
        ipv4_address: 10.0.2.15

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
